Ft login functionality #184359072
atlp-rwanda/team-emma-25-e-comm-backend pull request #17
Opened 2023-02-15 02:40 UTC by fabrice-rw

2023-02-16 10:08 UTC, jeandamas approved these changes, later dismissed

2023-02-17 14:56 UTC, key-joshua commented
Check some of your tests are not failing to pass and also resolve conflicts

2023-02-17 14:57 UTC, key-joshua commented
Check some of your tests are failing to pass and also resolve conflicts

2023-02-17 14:57 UTC, key-joshua commented
Check some of your tests are failing to pass and also resolve conflicts as well.

2023-02-17 14:58 UTC, key-joshua commented
Check some of checks are failing to pass and also resolve conflicts

2023-02-17 19:10 UTC, TresorRw approved these changes

2023-02-17 20:07 UTC, EmyRukundo requested changes

2023-02-17 20:07 UTC, EmyRukundo commented on src/routes/authroutes.ts
> +// router.post('/logout', auth.logout)
any reason for this ?

2023-02-17 20:07 UTC, EmyRukundo commented on src/controllers/authController.ts
> +        // console.log(decreptedPassword)
remove this

2023-02-17 20:07 UTC, EmyRukundo commented on src/controllers/authController.ts
> +      // await USER.drop()
you can remove this

2023-02-17 20:07 UTC, EmyRukundo commented on src/controllers/authController.ts
>  import USER from '../models/User'
Hi Fabrice, I can not see the test codes >

2023-02-18 12:22 UTC, Rukundojoseph approved these changes

2023-02-20 05:17 UTC, EmyRukundo approved these changes

2023-02-20 05:17 UTC, merged