FT: Manage user roles/permissions
atlp-rwanda/team-emma-25-e-comm-backend pull request #18
Opened 2023-02-16 13:00 UTC by jeandamas

- update user role

2023-02-17 20:08 UTC, EmyRukundo requested changes
I do not see the file changes

2023-02-27 07:53 UTC, jeandamas commented
### User roles and permissions FT -  This PR:

- Moves the user model into db repository 
- Update models in db to use TS
- Creates Role.ts model
- Makes Role names unique and lowercase to avoid duplicates in user roles

2023-02-27 13:11 UTC, Rukundojoseph approved these changes, later dismissed

2023-02-27 13:23 UTC, KABANOFESTO approved these changes, later dismissed

2023-03-04 13:15 UTC, rachelumwari approved these changes

2023-03-04 20:28 UTC, Rukundojoseph approved these changes

2023-03-05 14:29 UTC, merged