resolve duplicated modules, remove loginValidation, add login-swaggerUI
atlp-rwanda/team-emma-25-e-comm-backend pull request #19
Opened 2023-02-20 23:58 UTC by fabrice-rw

2023-02-21 09:10 UTC, TresorRw approved these changes, later dismissed

2023-02-21 21:41 UTC, key-joshua requested changes
From Login Function:: Create authHelpers/authRepository directory where you will have all your functions to interact with the database table. And move all sequelize methods logic or database queries into that create directory, this should be in that created helpers.

```
const findUser = await USER.findOne({
        where: { email: email },
        attributes: ['id', 'firstName', 'lastName', 'email', 'role', 'password'],
      })
```

2023-02-21 21:54 UTC, key-joshua requested changes
remove this compare password from authController [`const decreptedPassword = await bcrypt.compare(password, dbPassword)`](https://github.com/atlp-rwanda/e-comm-team-emma25-bn/blob/c3c694c3589456e1c94a94506e2357b0489ef95b/src/controllers/authController.ts#L132) and then create passwordHelper which will have all password related functionalities such as comparing password and hashing password functionality, etc...

Also, think about _**only saving user id into the token**_ and once a user provided a token when needs to access a given endpoint. Use that id to get all other related user details such as email, role, etc ... and then append them to the coming request. _**Otherwise, you will still having an invalid role in generated token once the user role is changed.**_

[`token: encode({ id: findUser.dataValues.id, email: findUser.dataValues.email, role: findUser.dataValues.role })`](https://github.com/atlp-rwanda/e-comm-team-emma25-bn/blob/c3c694c3589456e1c94a94506e2357b0489ef95b/src/controllers/authController.ts#L139)

2023-02-27 21:58 UTC, fabrice-rw commented
> remove this compare password from authController [`const decreptedPassword = await bcrypt.compare(password, dbPassword)`](https://github.com/atlp-rwanda/e-comm-team-emma25-bn/blob/c3c694c3589456e1c94a94506e2357b0489ef95b/src/controllers/authController.ts#L132) and then create passwordHelper which will have all password related functionalities such as comparing password and hashing password functionality, etc...
> 
> Also, think about _**only saving user id into the token**_ and once a user provided a token when needs to access a given endpoint. Use that id to get all other related user details such as email, role, etc ... and then append them to the coming request. _**Otherwise, you will still having an invalid role in generated token once the user role is changed.**_
> 
> [`token: encode({ id: findUser.dataValues.id, email: findUser.dataValues.email, role: findUser.dataValues.role })`](https://github.com/atlp-rwanda/e-comm-team-emma25-bn/blob/c3c694c3589456e1c94a94506e2357b0489ef95b/src/controllers/authController.ts#L139)

Note that when a user's role is changed, the token will still contain the old role until the token expires and a new token is generated

2023-03-06 12:26 UTC, closed without merging