Ft email verification
atlp-rwanda/team-emma-25-e-comm-backend pull request #20
Opened 2023-02-21 05:00 UTC by rachelumwari

Email verification

2023-02-21 09:12 UTC, TresorRw approved these changes, later dismissed

2023-02-21 12:21 UTC, jeandamas approved these changes, later dismissed

2023-02-24 08:46 UTC, EmyRukundo requested changes

2023-02-24 08:46 UTC, EmyRukundo commented on src/helper/sendMail.ts
> +// interface message_body {
you can remove this unused codes

2023-02-24 08:46 UTC, EmyRukundo commented on src/helper/sendMail.ts
> +  console.log(message_body)
you can remove this console

2023-02-24 08:46 UTC, EmyRukundo commented on src/controllers/authController.ts
>        //   const hash = await bcrypt.hashSync(password, 10)
unused codes

2023-03-13 13:16 UTC, TresorRw approved these changes

2023-03-13 18:30 UTC, closed without merging