Bg fix profile page validations
atlp-rwanda/team-emma-25-e-comm-backend pull request #26
Opened 2023-03-01 15:17 UTC by Rukundojoseph

**Title: Add birthdate validation and tests**

**Description:**
This pull request adds validation for the birthdate field in the profileDetails object using the 'joi' library. The validation ensures that the date is in the format 'YYYY-MM-DD' and that the user is at least 10 years old and no more than 150 years old.

**The pull request includes the following changes:**

- Added a custom validation function for the birthdate field that checks the date format and age of the user.
- Updated the profile schema to use the custom validation function for the birthdate field.
- Added unit tests to ensure that the validation function works as expected.

This change improves the accuracy and security of the application by ensuring that users provide valid and appropriate birthdate information.

**Screenshots:**
N/A

Testing:
- Run 'npm test' to verify that all tests pass.
- Manually test the profile form with valid and invalid birthdate inputs.

2023-03-05 17:54 UTC, jeandamas submitted a review, later dismissed

2023-03-06 06:25 UTC, KABANOFESTO approved these changes, later dismissed

2023-03-06 08:57 UTC, jeandamas approved these changes, later dismissed

2023-03-06 18:29 UTC, fabrice-rw approved these changes, later dismissed

2023-03-06 19:06 UTC, TresorRw approved these changes, later dismissed

2023-03-07 05:35 UTC, EmyRukundo requested changes
Kindly also squash the commits

2023-03-07 05:35 UTC, EmyRukundo commented on src/controllers/__tests__/authController.test.ts
> +  // test("incase of a registered email", async () => {
you should remove this

2023-03-07 05:35 UTC, EmyRukundo commented on src/controllers/__tests__/authController.test.ts
> +    //   expect(response.status).toBe(400);
you should remove this too

2023-03-07 06:51 UTC, EmyRukundo approved these changes

2023-03-07 06:52 UTC, merged